-- Generated by set-wallpaper. Do not edit by hand.
return {
    accent   = "rgba(b8aa89ff)",
    dim      = "rgba(8e8571ff)",
    muted    = "rgba(4d4942ff)",
    bg       = "rgba(131211ff)",
    bg_plain = "rgb(131211)",
    accent_plain = "rgb(b8aa89)",
    dim_plain    = "rgb(8e8571)",
}
