-- Generated by set-wallpaper. Do not edit by hand.
return {
    accent   = "rgba(8492beff)",
    dim      = "rgba(6e7791ff)",
    muted    = "rgba(41444eff)",
    bg       = "rgba(101113ff)",
    bg_plain = "rgb(101113)",
    accent_plain = "rgb(8492be)",
    dim_plain    = "rgb(6e7791)",
}
