-- Generated by set-wallpaper. Do not edit by hand.
return {
    accent   = "rgba(d96868ff)",
    dim      = "rgba(a25d5dff)",
    muted    = "rgba(543b3bff)",
    bg       = "rgba(150f0fff)",
    bg_plain = "rgb(150f0f)",
    accent_plain = "rgb(d96868)",
    dim_plain    = "rgb(a25d5d)",
}
