source = ~/.config/hypr/lock-colors.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.012
    contrast = 0.9
    brightness = 0.7
    vibrancy = 0.17
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    outer_color = $accent
    inner_color = $bg_alt
    font_color = $lightest
    check_color = $light
    fail_color = $warn

    fade_on_empty = false
    placeholder_text = <span foreground="##$dim_hex">Password</span>
    fail_text = <span foreground="##$warn_hex">Wrong</span>

    rounding = 10
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = $lightest
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:3600000] date +"%A, %d %B"
    color = $accent
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}
